config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :people do
    resources :tracks
  end

  resources :tracks do
    collection do
      get 'find'
    end
  end

  resources :branches  do
    resources :people
  end
  resources :companies
  get 'pages/home'
  # devise_for :users
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  get 'site', to: 'site#index'

  root 'pages#home'
  #root "site#index"
end

app/models/track.rb
# frozen_string_literal: true

class Track < ApplicationRecord
  after_update_commit { broadcast_append_to 'tracks' }
  belongs_to :branch
  belongs_to :assigned, class_name: 'Person'
  belongs_to :owner, class_name: 'User'
  validates :code, presence: true
  validates :code, uniqueness: true
  enum status: { delivered: 0, received: 1 }

  def branch_name
    branch.try(:name)
  end

  def assigned_name
    assigned.try(:name)
  end
end

app/controllers/tracks_controller.rb
# frozen_string_literal: true

class TracksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_track, only: %i[show edit update destroy]

  def default_assigned_id
    session[:person_id] = params[:person_id] if params[:person_id].present?
    assigned_id = session[:person_id]
    puts "assigned_id #{assigned_id}"
    return assigned_id
  end
  helper_method :default_assigned_id

  def default_assigned_name
     Person.where(id: default_assigned_id).pluck(:name)[0]
  end
  helper_method :default_assigned_name

  def default_branch_id
    Person.where(id: default_assigned_id).pluck(:branch_id)[0]
  end
  helper_method :default_branch_id

  def default_branch_name
    Branch.where(id: default_branch_id).pluck(:name)[0]
  end
  helper_method :default_branch_name

  # GET /tracks or /tracks.json
  def index
    @pagy, @tracks = pagy(Track.where(owner_id: current_user.id,
                          assigned_id: session[:person_id]).where("code LIKE ?",
                                                          "%#{params[:filter]}%").order(status: :asc, created_at: :asc))
  end

  # GET /tracks/1 or /tracks/1.json
  def show; end

  # GET /tracks/new
  def new
    @track = Track.new
  end

  # GET /tracks/1/edit
  def edit; end

  # POST /tracks or /tracks.json
  def create
    @track = Track.new(track_params)
    @track.owner_id = current_user.id
    @track.status = 0
    respond_to do |format|
      if @track.save
        format.turbo_stream
        format.html { redirect_to track_url(@track), notice: 'Track was successfully created.' }
      else
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace("#{helpers.dom_id(@track)}_form", partial: 'form',
                                                                                      locals: { track: @track })
        end
      end
    end
  end

  # PATCH/PUT /tracks/1 or /tracks/1.json
  def update
    respond_to do |format|
      if @track.update(track_params)
        format.html { redirect_to track_url(@track), notice: 'Track was successfully updated.' }
      else
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace("#{helpers.dom_id(@track)}_form", partial: 'form',
                                                                                      locals: { track: @track })
        end
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tracks/1 or /tracks/1.json
  def destroy
    @track.destroy

    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove("#{helpers.dom_id(@track)}_item") }
      format.html { redirect_to tracks_url, notice: 'Track was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def find
    @tracks = Track.where(owner_id: current_user.id).where("code LIKE ?","%#{params[:query_track]}%").order(code: :asc)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_track
    @track = Track.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def track_params
    params.require(:track).permit(:code, :status, :branch_id, :assigned_id, :owner_id)
  end
end

app/helpers/tracks_helper.rb
# frozen_string_literal: true

module TracksHelper

end

app/views/tracks/_form.html.erb
<%= form_with(model: track, id:"#{dom_id(track)}_form") do |form| %>
  <% if track.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(track.errors.count, "error") %> prohibited this track from being saved:</h2>

      <ul>
        <% track.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-6">
    <%= form.label t(:code), class: "sr-only" %>
    <div class="relative">
      <%= form.text_field :code, autofocus: true, class: "block shadow-sm rounded-full border border-gray-200 outline-none px-6 py-4 w-full focus:border-sky-300 focus:outline-none focus:ring-4 focus:ring-sky-50 text-lg placeholder:text-gray-400", placeholder: t(:add_new_track) %>
      <%= form.hidden_field :assigned_id, value: default_assigned_id %>
      <%= form.hidden_field :branch_id, value: default_branch_id %>
    <div class="absolute top-0 right-0">
      <%= form.submit class: "mt-px rounded-full py-4 px-5 bg-skye-500 text-white font-medium cursor-pointer border-2 border-sky-500 hover:bg-sky-600 hover:border-sky-600" %>
    </div>
  </div>
</div>
<%= render :partial => 'shared/form_focus', :locals => {:focusField => 'code'} -%>
<% end %>

app/views/tracks/_track.html.erb
<li id="<%= "#{dom_id(track)}_item" %>" class="py-3">
    <%= turbo_frame_tag dom_id(track) do %>
        <div class="flex items-center justify-between">
            <%= link_to track.code+' '+track.created_at.in_time_zone("America/Bogota").utc.strftime('%m/%d/%Y %H:%M %p'), edit_track_path(track), class: "flex-1 #{"line-throuht opacity-70" if track.delivered?}" %>

            <div class="flex items-center space-x-3">
                <% if track.delivered? %>
                    <%= button_to t(:mark_received), track_path(track, track: { status:  'received'}), method: :patch, class: "bg-teal-500 px-3 py-2 rounded inline-flex items-center justify-center text-white-600" %>
                <% else %>
                    <%= button_to t(:mark_delivered), track_path(track, track: { status:  'delivered'}), method: :patch, class: "bg-gray-500 px-3 py-2 rounded inline-flex items-center justify-center text-white-600" %>
                <% end %>
            </div>

            <%= button_to t(:delete), track_path(track), method: :delete, class: "bg-red-500 px-3 py-2 rounded inline-flex items-center justify-center text-white-600" %>
        </div>
    <% end %>
</li>

app/views/tracks/create.turbo_stream.erb
<%= turbo_stream.prepend "tracks" do %>
    <%= render "track", track: @track %>
<% end %>

<%= turbo_stream.replace "#{dom_id(Track.new)}_form" do %>
    <%= render "form", track: Track.new %>
<% end %>

app/views/tracks/edit.html copy.erb
<%= form_with(model: track, id:"#{dom_id(track)}_form") do |form| %>
  <% if track.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(track.errors.count, "error") %> prohibited this track from being saved:</h2>

      <ul>
        <% track.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-6">
    <%= form.label t(:code), class: "sr-only" %>
    <div class="relative">
      <%= form.text_field :code, autofocus: true, class: "block shadow-sm rounded-full border border-gray-200 outline-none px-6 py-4 w-full focus:border-sky-300 focus:outline-none focus:ring-4 focus:ring-sky-50 text-lg placeholder:text-gray-400", placeholder: t(:add_new_track) %>
      <div class="my-5">
        <%= form.label t(:person) %>
        <%= form.collection_select :assigned_id,  Person.all.order(:name).where(branch_id: :branch_id), :id, :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
      </div>
    <div class="absolute top-0 right-0">
      <%= form.submit class: "mt-px rounded-full py-4 px-5 bg-skye-500 text-white font-medium cursor-pointer border-2 border-sky-500 hover:bg-sky-600 hover:border-sky-600" %>
    </div>
  </div>
</div>
<% end %>

app/views/tracks/edit.html.erb
<%= form_with(model: @track, class: "contents") do |form| %>
  <% if @track.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(@track.errors.count, "error") %> prohibited this track from being saved:</h2>

      <ul>
        <% @track.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label t(:code) %>
    <%= form.text_field :code, autofocus: true, class: "block shadow-sm rounded-full border border-gray-200 outline-none px-6 py-4 w-full focus:border-sky-300 focus:outline-none focus:ring-4 focus:ring-sky-50 text-lg placeholder:text-gray-400" %>
  </div>

  <div class="my-5">
    <%= form.label t(:branch) %>
    <%= select_tag :branch_id, options_from_collection_for_select(@branches, "id","name", @branch&.id), prompt: "-Select -", onchange: "this.form.submit()" %>
    <%# form.collection_select :branch_id, Branch.all.order(:name).where(user_id: current_user.id), :id, :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label t(:person) %>
    <%= form.collection_select :assigned_id,  Person.all.order(:name), :id, :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit t(:update), class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/tracks/find.html.erb
<div class="mx-auto max-w-3xl mt-24">
  <h1 class="font-bold text-4xl mb-6">
    <%= t(:tracks) %> <%= t(:begin_with) %> <%= params[:query_track] %>
  </h1>

  <div class="flex mt-12 items-center justify-center space-x-4 w-full">
  </div>
  <table class="table-auto">
    <thead>
      <tr>
        <th><%=t(:code) %></th>
        <th><%=t(:assigned) %></th>
        <th><%=t(:branch) %></th>
        <th><%=t(:created) %></th>
        <th><%=t(:modify) %></th>
      </tr>
    </thead>
    <tbody>
      <% @tracks.each do |track| %>
          <tr>
          <td><%= track.code %></td>
          <td><%= track.assigned_name %></td>
          <td><%= track.branch_name %></td>
          <td><%= track.created_at.in_time_zone("America/Bogota").utc.strftime('%m/%d/%Y') %></td>
          <td> <%# link_to t(:edit), edit_track_path(track), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %></td>
          <td><%= link_to :sites, site_path, data: {action: "click->dropdown#toggle"}, class: "rounded-none py-3 px-5 bg-teal-500 hover:bg-teal-600 active:bg-teal-700 focus:outline-none focus:ring focus:ring-gray-300 text-white block font-medium"  %> <%# link_to t(:edit), sites_path, class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
          </td>
          <td>
          <div class="flex items-center space-x-3">
          <% if track.delivered? %>
              <%= button_to t(:mark_received), track_path(track, track: { status:  'received'}), method: :patch, class: "bg-teal-500 px-3 py-2 rounded inline-flex items-center justify-center text-white-600" %>
          <% else %>
              <%= button_to t(:mark_delivered), track_path(track, track: { status:  'delivered'}), method: :patch, class: "bg-gray-500 px-3 py-2 rounded inline-flex items-center justify-center text-white-600" %>
          <% end %>
          </td>
      </div>
          </tr>
      <% end %>
    </tbody>
  </table>



  <div class="flex mt-12 items-center justify-center space-x-4 w-full">
    <div class="inline">

    </div>
  </div>
</div>

app/views/tracks/findx.html.erb
<%= turbo_frame_tag "modal" do %>
  <div class="modal">
    <h1 class="font-bold text-4xl mb-6"> <%= t(:tracks) %> <%= "Modal" %>
    </h1>
    <%= render 'tracks' %>
    <div>
      <%= link_to "Cancel", "#", data: {
          controller: "modals",
          action: "modals#close"
      }, class: "cancel-button" %>
    </div>
  </div>
<% end %>

app/views/tracks/index.html.erb
<div class="mx-auto max-w-3xl mt-24">
  <h1 class="font-bold text-4xl mb-6">
    <%= t(:tracks) %> <%= t(:for) %>
    <%= link_to default_assigned_name, branch_people_path(default_branch_id), method: :get, class: "flex-1 #{"line-throuht opacity-50" }" %>
    <%= t(:branch) %>
    <%= link_to default_branch_name,  branches_path, method: :get, class: "flex-1 #{"line-throuht opacity-50" }" %>
  </h1>

  <%= render "form", track: Track.new %>

  <div>
    <%= form_with url: tracks_path, method: :get, data: { turbo_frame: "tracks", controller: "search_form", action: "input->search_form#submit" } do %>
        <%= text_field_tag "filter", nil, placeholder: t(:filter), class: "justify-items-end inline-block rounded-md border  border-gray-200 outline-none px-3 py-2 w-1/2", autocomplete: "off" %>
    <% end %>
  </div>

  <div class="flex mt-12 items-center justify-center space-x-4 w-full">
    <%== pagy_nav(@pagy) %>
  </div>

  <%= turbo_frame_tag "tracks" do  %>
    <ul id="tracks" class="divide-y list-none">
      <%= render @tracks %>
    </ul>
  <% end %>

  <div class="flex mt-12 items-center justify-center space-x-4 w-full">
    <%== pagy_nav(@pagy) %>
  </div>
</div>

app/views/tracks/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New track</h1>

  <%= render "form", track: @track %>

  <%= link_to 'Back to tracks', tracks_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/tracks/person_tracks.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New track</h1>

  <%= render "form", track: @track %>

  <%= link_to 'Back to tracks', tracks_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/tracks/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @track %>  

    <%= link_to 'Edit this track', edit_track_path(@track), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this track', track_path(@track), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to tracks', tracks_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>