config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :people do
    resources :tracks
  end

  resources :tracks do
    collection do
      get 'find'
    end
  end

  resources :branches  do
    resources :people
  end
  resources :companies
  get 'pages/home'
  # devise_for :users
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  get 'site', to: 'site#index'

  root 'pages#home'
  #root "site#index"
end

app/models/person.rb
# frozen_string_literal: true

class Person < ApplicationRecord
  after_update_commit { broadcast_append_to 'people' }
  belongs_to :branch
  validates :name, presence: true, format: { with: /\A[a-zA-Z ]+\Z/ }
  validates :mobile, presence: true, uniqueness: true, numericality: { only_integer: true }
  validates :nid, uniqueness: true, numericality: { only_integer: true }
  validates :email, email: { mode: :strict, require_fqdn: true }

  has_many :track_as_assigned, foreign_key: 'assigned_id', class_name: 'Track'
end

app/controllers/people_controller.rb
# frozen_string_literal: true

class PeopleController < ApplicationController
  before_action :authenticate_user!
  before_action :set_person, only: %i[show edit update destroy]

  # def branch_name
  #   Branch.find(user_id: current_user.id).first.name
  # end
  # helper_method :branch_name

  # GET /people or /people.json
  def index
    @people = Person.where(branch_id: default_branch_id)
  end

  def default_branch_id
    params[:branch_id].present? ? params[:branch_id] : @person.branch_id
  end
  helper_method :default_branch_id

  def default_branch_name
    return Branch.where(id: default_branch_id).pluck(:name)[0]
  end
  helper_method :default_branch_name

  # GET /people/1 or /people/1.json
  def show; end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit; end

  # POST /people or /people.json
  def create
    @person = Person.new(person_params)
    respond_to do |format|
      if @person.save
        format.turbo_stream
        format.html { redirect_to person_url(@person), notice: 'Person was successfully created.' }
      else
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace("#{helpers.dom_id(@person)}_form", partial: 'form',
                                                                                       locals: { person: @person })
        end
      end
    end
  end

  # PATCH/PUT /people/1 or /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to person_url(@person), notice: 'Person was successfully updated.' }
      else
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace("#{helpers.dom_id(@person)}_form", partial: 'form',
                                                                                       locals: { todo: @todo })
        end
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1 or /people/1.json
  def destroy
    @person.destroy

    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove("#{helpers.dom_id(@person)}_item") }
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_person
    @person = Person.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def person_params
    params.require(:person).permit(:email, :name, :citizenship, :nid, :mobile, :branch_id)
  end
end

app/helpers/people_helper.rb
# frozen_string_literal: true

module PeopleHelper
end

app/views/people/_form.html.erb
<%= form_with(model: person, id:"#{dom_id(person)}_form") do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
        <% person.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :branch_id, value: default_branch_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  <div class="my-5">
    <%= form.label t(:name) %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", autocomplete: "off"  %>
  </div>

  <div class="my-5">
    <%= form.label t(:email) %>
    <%= form.text_field :email, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", autocomplete: "off"  %>
  </div>

  <div class="my-5">
    <%= form.label t(:citizenship) %>
    <%= form.country_select :citizenship, priority_countries: ["CO"], class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", autocomplete: "off"  %>
  </div>

  <div class="my-5">
  </div>

  <div class="my-5">
    <%= form.label :nid %>
    <%= form.number_field :nid, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label t(:mobile) %>
    <%= form.telephone_field :mobile, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/people/_person.html.erb
<li id="<%= "#{dom_id(person)}_item" %>" class="py-3">
    <%= turbo_frame_tag dom_id(person) do %>
        <div class="flex items-center justify-between">
          <%= link_to person.name+' '+person.mobile+' '+ person.email, edit_person_path(person), class: "flex-1 #{"line-throuht opacity-50" }" %>
          <%# button_to Tracks", tracks_path, method: :get, class: "bg-teal-500 px-3 py-2 rounded inline-flex items-center justify-center text-white-600" %>
          <%= button_to t(:tracks), person_tracks_path(person), method: :get, class: "bg-teal-500 px-3 py-2 rounded inline-flex items-center justify-center text-white-600" %>
          <%= button_to t(:delete), person_path(person), method: :delete, class: "bg-red-500 px-3 py-2 rounded inline-flex items-center justify-center text-white-600" %>
        </div> 
    <% end %>
</li>

app/views/people/create.turbo_stream.erb
<%= turbo_stream.prepend "people" do %>
    <%= render "person", person: @person %>
<% end %>

<%= turbo_stream.replace "#{dom_id(Person.new)}_form" do %>
    <%= render "form", person: Person.new %>
<% end %>

app/views/people/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl"> <%= t(:editing) %>  <%= t(:person) %></h1>

  <%= render "form", person: @person %>

  <%= link_to t(:show), @person, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to t(:back), people_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/people/index.html.erb
<div class="mx-auto max-w-3xl mt-24">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice">
      <%= notice %></p>
  <% end %>

    <h1 class="font-bold text-4xl"> <%= t(:people) %>
      <%= t(:of) %>
      <%= t(:branch) %>
      <%= link_to default_branch_name,  branches_path, method: :get, class: "flex-1 #{"line-throuht opacity-50" }" %>
    </h1>
    <%= render "form", person: Person.new %>

    <%= turbo_stream_from "people" %>

  <ul id="people" class="divide-y list-none">
    <%= render @people %>
  </ul>
</div>

app/views/people/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New person</h1>

  <%= render "form", person: @person %>

  <%= link_to 'Back to people', people_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/people/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @person %>

    <%= link_to 'Edit this person', edit_person_path(@person), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this person', person_path(@person), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to people', people_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>