config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :people do
    resources :tracks
  end

  resources :tracks do
    collection do
      get 'find'
    end
  end

  resources :branches  do
    resources :people
  end
  resources :companies
  get 'pages/home'
  # devise_for :users
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  get 'site', to: 'site#index'

  root 'pages#home'
  #root "site#index"
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">

 <nav class="flex items-center justify-between flex-wrap bg-teal-500 p-6">
  <div class="flex items-center flex-shrink-0 text-white mr-6">
    <img id="rackMyPaper" src="<%= asset_path('LogoTrackMyPaper_BVGT.png') %>" draggable="true" ondragstart="drag(event)" width="26" height="43">
    <span class="font-semibold text-xl tracking-tight"> <%= t(:header_trackofmypapers) %> </span>
  </div>
  <div class="block lg:hidden">
    <button class="flex items-center px-3 py-2 border rounded text-teal-200 border-teal-400 hover:text-white hover:border-white">
      <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
    </button>
  </div>


  <div class="w-full block flex-grow lg:flex lg:items-center lg:w-auto">
      <% if current_user %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="true" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <%= link_to t(:home), root_path, data: {action: "click->dropdown#toggle"}, class: "rounded-none py-3 px-5 bg-teal-500 hover:bg-teal-600 active:bg-teal-700 focus:outline-none focus:ring focus:ring-gray-300 text-white block font-medium"  %>
        <%# link_to :sites, site_path, data: {action: "click->dropdown#toggle"}, class: "rounded-none py-3 px-5 bg-teal-500 hover:bg-teal-600 active:bg-teal-700 focus:outline-none focus:ring focus:ring-gray-300 text-white block font-medium"  %>


        <div>
        <%= form_with url: find_tracks_path, method: :get, data: { turbo_frame: "modal", controller: "find_form", action: "input->find_form#submit" } do %>
            <%= text_field_tag :query_track, nil, placeholder: t(:find_track), class: "justify-items-end inline-block rounded-md border  border-gray-200 outline-none px-3 py-2 w-2/3", autocomplete: "off" %>
        <% end %>
        </div>

        <%# link_to t(:companies), companies_path, data: {action: "click->dropdown#toggle"}, class: "rounded-none py-3 px-5 bg-teal-500 hover:bg-teal-600 active:bg-teal-700 focus:outline-none focus:ring focus:ring-gray-300 text-white block font-medium"  %>
        <%# link_to t(:branches), branches_path, data: {action: "click->dropdown#toggle"}, class: "rounded-none py-3 px-5 bg-teal-500 hover:bg-teal-600 active:bg-teal-700 focus:outline-none focus:ring focus:ring-gray-300 text-white block font-medium" %>
        <%# link_to t(:people), people_path, data: {action: "click->dropdown#toggle"}, class: "rounded-none py-3 px-5 bg-teal-500 hover:bg-teal-600 active:bg-teal-700 focus:outline-none focus:ring focus:ring-gray-300 text-white block font-medium" %>
        <%# link_to t(:tracks), tracks_path, data: {action: "click->dropdown#toggle"}, class: "rounded-none py-3 px-5 bg-teal-500 hover:bg-teal-600 active:bg-teal-700 focus:outline-none focus:ring focus:ring-gray-300 text-white block font-medium" %>
        <strong>  Your are <%= current_user.email %></strong>
        <%= link_to t(:log_out), destroy_user_session_path, data: { turbo_method: "delete" }, class: "rounded-none py-3 px-5 bg-teal-500 hover:bg-teal-600 active:bg-teal-700 focus:outline-none focus:ring focus:ring-gray-300 text-white block font-medium" %>
      <% else %>
        <%= link_to t(:log_in), new_user_session_path, data: {action: "click->dropdown#toggle"}, class: "rounded-none py-3 px-5 bg-teal-500 hover:bg-teal-600 active:bg-teal-700 focus:outline-none focus:ring focus:ring-gray-300 text-white block font-medium" %>
        <%= link_to t(:sign_up), new_user_registration_path, data: {action: "click->dropdown#toggle"}, class: "rounded-none py-3 px-5 bg-teal-500 hover:bg-teal-600 active:bg-teal-700 focus:outline-none focus:ring focus:ring-gray-300 text-white block font-medium" %>
      <% end %>
    </div>
  </div>
  <div>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </div>
</nav>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t(:tguide) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag asset_path('LogoTrackMyPaper_RVGT.png') %>
  </head>

  <body "bg-gradient-to-r from-pink-50 to-sky-50 container px-12 xl:px-0 py-24 mx-auto max-w-5xl antialiased">
    <header class="navbar navbar-fixed-top navbar-inverse">
      <%= render 'layouts/header' %>
      <div id="container">
    </header>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= turbo_frame_tag "modal" %>
      <%= yield %>
    </main>
  </body>
</html>